<?php
//Define interface class for router
use \Psr\Http\Message\ServerRequestInterface as Request;    //PSR7 ServerRequestInterface   >> Each router file must contains this
use \Psr\Http\Message\ResponseInterface as Response;        //PSR7 ResponseInterface        >> Each router file must contains this

//Define your modules class
use \modules\invoice\Invoice as Invoice;                    //Your main modules class

//Define additional class for any purpose
use \classes\middleware\ApiKey as ApiKey;                   //ApiKey Middleware             >> To authorize request by using ApiKey generated by reSlim

    
    // Get module information (include cache and for public user)
    $app->map(['GET','OPTIONS'],'/invoice/get/info/', function (Request $request, Response $response) {
        $i = new Invoice($this->db);
        $body = $response->getBody();
        $response = $this->cache->withEtag($response, $this->etag2hour.'-'.trim($_SERVER['REQUEST_URI'],'/'));
        $body->write($i->viewInfo());
        return classes\Cors::modify($response,$body,200,$request);
    })->add(new ApiKey);

    // Installation 
    $app->get('/invoice/install/{username}/{token}', function (Request $request, Response $response) {
        $i = new Invoice($this->db);
        $i->lang = (empty($_GET['lang'])?$this->settings['language']:$_GET['lang']);
        $i->username = $request->getAttribute('username');
        $i->token = $request->getAttribute('token');
        $body = $response->getBody();
        $body->write($i->install());
        return classes\Cors::modify($response,$body,200);
    });

    // Uninstall (This will clear all data) 
    $app->get('/invoice/uninstall/{username}/{token}', function (Request $request, Response $response) {
        $i = new Invoice($this->db);
        $i->lang = (empty($_GET['lang'])?$this->settings['language']:$_GET['lang']);
        $i->username = $request->getAttribute('username');
        $i->token = $request->getAttribute('token');
        $body = $response->getBody();
        $body->write($i->uninstall());
        return classes\Cors::modify($response,$body,200);
    });